/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import { TimeAllyManager } from "./TimeAllyManager";

export class TimeAllyManagerFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TimeAllyManager {
    return new Contract(address, _abi, signerOrProvider) as TimeAllyManager;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_month",
        type: "uint256"
      }
    ],
    name: "getTotalActiveStaking",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_stakingContract",
        type: "address"
      }
    ],
    name: "isStakingContractValid",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool"
      }
    ],
    stateMutability: "view",
    type: "function"
  }
];
