/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface TimeAllyManagerInterface extends ethers.utils.Interface {
  functions: {
    "getTotalActiveStaking(uint256)": FunctionFragment;
    "isStakingContractValid(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getTotalActiveStaking",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isStakingContractValid",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getTotalActiveStaking",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isStakingContractValid",
    data: BytesLike
  ): Result;

  events: {};
}

export class TimeAllyManager extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: TimeAllyManagerInterface;

  functions: {
    getTotalActiveStaking(
      _month: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getTotalActiveStaking(uint256)"(
      _month: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    isStakingContractValid(
      _stakingContract: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "isStakingContractValid(address)"(
      _stakingContract: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;
  };

  getTotalActiveStaking(
    _month: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getTotalActiveStaking(uint256)"(
    _month: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  isStakingContractValid(
    _stakingContract: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "isStakingContractValid(address)"(
    _stakingContract: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    getTotalActiveStaking(
      _month: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getTotalActiveStaking(uint256)"(
      _month: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isStakingContractValid(
      _stakingContract: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isStakingContractValid(address)"(
      _stakingContract: string,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    getTotalActiveStaking(
      _month: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getTotalActiveStaking(uint256)"(
      _month: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isStakingContractValid(
      _stakingContract: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isStakingContractValid(address)"(
      _stakingContract: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getTotalActiveStaking(
      _month: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getTotalActiveStaking(uint256)"(
      _month: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isStakingContractValid(
      _stakingContract: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isStakingContractValid(address)"(
      _stakingContract: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
